---
abstract: 'IO::Storm allows you to write Bolts and Spouts for Storm in Perl.'
author:
  - 'Dan Blanchard <dblanchard@ets.org>'
  - 'Cory G Watson <gphat@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Storm
requires:
  JSON::XS: '0'
  Log::Log4perl: '0'
  Moo: '0'
  Test::MockObject: '0'
  Test::More: '0'
  Test::Output: '0'
  Try::Tiny: '0'
  namespace::clean: '0'
version: '0.09'
